{{- range .roles }}
---
{{- if eq .role_binding true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "kubeinfo-backend.labels" $ | nindent 4 }}
  name: {{ include "kubeinfo-backend.name" $ }}-{{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeinfo-backend.name" $ }}-{{ .name }}
subjects:
- kind: {{ .kind }}
  name: {{ include "kubeinfo-backend.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}