{{- range .roles }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "kubeinfo-backend.labels" $ | nindent 4 }}
  name: {{ include "kubeinfo-backend.name" $ }}-{{ .name }}
rules: 
{{ toYaml .rules }}
{{- end }}
{{- end }}