// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nodes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get info about nodes in cluster",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kubeApiResponseStruct.NodeRespose"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "kubeApiResponseStruct.NodeRespose": {
            "type": "object",
            "properties": {
                "contolplanenumber": {
                    "type": "integer"
                },
                "kubernetesversion": {
                    "type": "string"
                },
                "nodenumber": {
                    "type": "integer"
                },
                "osimage": {
                    "type": "string"
                },
                "workernumber": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "kubeinfo-kubeinfo-backend.kubeinfo.svc",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kubeinfo API",
	Description:      "Kubeinfo used to get information about k8s cluster component",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
