name: Build and Push
on:
  push:
    tags:
        - '*.*.*'
env:
  GO_VERSION: 1.19.1
permissions:
    contents: write
    packages: write
jobs:
    Deploy:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/randsw/kubeinfo
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
    Release:
        needs: Deploy
        name: "Release"
        runs-on: "ubuntu-latest"
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Check which branch belong commit with tag
          id: check-branch
          run: |
            onMainBranch=false
            branches=$(git branch -r --contains tags/$GITHUB_REF_NAME)
            for branch in $branches; do
              if [[ $branch == "origin/main" ]]; then
              onMainBranch=true
              fi
            done
            echo "onMainBranch=$onMainBranch" >> $GITHUB_OUTPUT
            echo $onMainBranch
          shell: bash
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            generate_release_notes: true
          if: ${{ steps.check-branch.outputs.onMainBranch }}
