name: kubeinfo
on:
  push:
    branches:
      - "main"
env:
  GO_VERSION: 1.19.1
jobs:
    # build workflow
    build:
      runs-on: ubuntu-latest
      steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run build
        run: go build .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2