name: Release Helm Chart

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'helm-chart/kubeinfo-backend/*.{yaml,tpl}'

permissions:
    contents: write
jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Get changed files in the docs folder
        id: changed-files-helm-chart
        uses: tj-actions/changed-files@v35
        with:
          files: helm-chart/kubeinfo-backend/*.{yaml,tpl}

      - name: List all changed files
        id: list-changed-files
        run: |
            echo "List all the files that have changed: ${{ steps.changed-files-helm-chart.outputs.all_changed_files }}"

      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        if: steps.changed-files-helm-chart.outputs.any_changed == 'true'
    
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
            charts_dir: helm-chart
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: steps.changed-files-helm-chart.outputs.any_changed == 'true'