name: Lint, Test and Release Charts
on:
  push:
    branches:
      - 'develop'
      - 'main'
    paths:
      - 'helm-chart/kubeinfo-backend/**/*.yaml'
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths:
      - 'helm-chart/kubeinfo-backend/**/*.yaml'
permissions:
  contents: write
jobs:
  Lint-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Get changed files in the helm folder
        id: changed-files-helm-chart
        uses: tj-actions/changed-files@v39
        with:
          files: helm-chart/kubeinfo-backend/*.{yaml,tpl}
          files_yaml: |
            helm:
              - helm-chart/kubeinfo-backend/*.{yaml,tpl}
              - '!helm-chart/kubeinfo-backend/Chart.yaml'
            chart_version:
              - 'helm-chart/kubeinfo-backend/Chart.yaml'

      - name: List all changed files
        id: list-changed-files
        run: |
            echo "List all the files that have changed: ${{ steps.changed-files-helm-chart.outputs.all_changed_files }}"

      - name: List chart changed files
        id: list-chart-changed-files
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files-helm-chart.outputs.helm_all_changed_files }}"

      - name: List chart version changed files
        id: list-chart-version-changed-files
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files-helm-chart.outputs.chart_version_all_changed_files }}"

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --all
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml --all
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true'
      
      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        if: github.ref == 'refs/heads/main'

      - name: Install PyBump
        run: |
          python3 -m pip install pybump
        shell: bash
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true' && steps.changed-files-helm-chart.outputs.chart_version_any_changed != 'true' && github.ref == 'refs/heads/main'

      - name: Automated Version Bump
        id: version-bump
        run: |
          pybump bump --file helm-chart/kubeinfo-backend/Chart.yaml --level patch
        shell: bash
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true' && steps.changed-files-helm-chart.outputs.chart_version_any_changed != 'true' && github.ref == 'refs/heads/main'

      - name: Output Name
        id: chart-name
        run: |
          echo "::set-output name=chart::$(basename helm-chart/kubeinfo-backend)"
        shell: bash
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true' && steps.changed-files-helm-chart.outputs.chart_version_any_changed != 'true' && github.ref == 'refs/heads/main'

      - name: GIT Commit
        run: |
          git add helm-chart/kubeinfo-backend/Chart.yaml
          git commit -m "Automatic bump Helm chart version"
          git push
        if: steps.changed-files-helm-chart.outputs.helm_any_changed == 'true' && steps.changed-files-helm-chart.outputs.chart_version_any_changed != 'true' && github.ref == 'refs/heads/main'
    
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
            charts_dir: helm-chart
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: steps.changed-files-helm-chart.outputs.chart_version_any_changed == 'true' && github.ref == 'refs/heads/main'

