name: Create semantic release
on:
  push:
    branches:
      - 'develop'
      - 'main'
    paths:
      - '**.go'
      - 'Dockerfile'
permissions:
  contents: write
jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v3
          with:
            semantic_version: 19
            # You can specify specifying version range for the extra plugins if you prefer.
            extra_plugins: |
                @semantic-release/changelog@6.0.1
                @semantic-release/git@10.0.1
                @semantic-release/commit-analyzer@9.0.2
                @semantic-release/release-notes-generator@11.0.1
                conventional-changelog-conventionalcommits@5.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}