name: Tests
on:
  push:
    branches:
      - '!main'
    paths:
      - '**.go'
  pull_request:
env:
  GO_VERSION: 1.19.1
jobs:
    # build workflow
    Test:
      runs-on: ubuntu-latest
      steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
    Lint:
      runs-on: ubuntu-latest
      steps:
        - name: set up go ${{env.GO_VERSION}}
          uses: actions/setup-go@v4
          with:
            go-version: ${{env.GO_VERSION}}
          id: go
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            args: --timeout 5m